# Generated by Django 3.2.8 on 2021-10-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurses',
            old_name='doctor_experience',
            new_name='nurse_name',
        ),
        migrations.RenameField(
            model_name='nurses',
            old_name='doctor_name',
            new_name='nurse_number',
        ),
        migrations.RenameField(
            model_name='nurses',
            old_name='doctor_patients',
            new_name='nurse_patients',
        ),
        migrations.RenameField(
            model_name='nurses',
            old_name='doctor_number',
            new_name='nurse_pin',
        ),
        migrations.RenameField(
            model_name='sawbones',
            old_name='doctor_work',
            new_name='doctor_pin',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='doctor_work',
            new_name='doctor_pin',
        ),
        migrations.RemoveField(
            model_name='hosp',
            name='del_info',
        ),
        migrations.RemoveField(
            model_name='hosp',
            name='id',
        ),
        migrations.RemoveField(
            model_name='maindoctor',
            name='del_info',
        ),
        migrations.RemoveField(
            model_name='maindoctor',
            name='doctor_work',
        ),
        migrations.RemoveField(
            model_name='nurses',
            name='del_info',
        ),
        migrations.RemoveField(
            model_name='nurses',
            name='doctor_work',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='del_info',
        ),
        migrations.RemoveField(
            model_name='sawbones',
            name='del_info',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='del_info',
        ),
        migrations.AddField(
            model_name='hosp',
            name='hosp_gos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hosp',
            name='hosp_okpo',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hosp',
            name='hosp_region',
            field=models.CharField(choices=[('1', 'Chui'), ('2', 'Yssyk-Kol'), ('3', 'Naryn'), ('4', 'Talas'), ('5', 'Djalal-Abad'), ('6', 'Osh'), ('7', 'Batken')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maindoctor',
            name='doctor_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maindoctor',
            name='doctor_pin',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurses',
            name='nurse_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='patient_age',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='patient_pin',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sawbones',
            name='doctor_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='doctor_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hosp',
            name='hosp_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maindoctor',
            name='doctor_experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sawbones',
            name='doctor_experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='doctor_experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='doctor_pasients',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='hospital',
        ),
    ]
