# Generated by Django 3.2.8 on 2021-10-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20211016_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_work', models.CharField(choices=[('1', 'Sawbones'), ('2', 'Therapist')], max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_pin', models.CharField(max_length=100)),
                ('doctor_age', models.IntegerField()),
                ('doctor_experience', models.IntegerField()),
                ('doctor_number', models.CharField(max_length=100)),
                ('doctor_patients', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Sawbones',
        ),
        migrations.DeleteModel(
            name='Therapist',
        ),
        migrations.RemoveField(
            model_name='maindoctor',
            name='doctor_sawbones',
        ),
        migrations.RemoveField(
            model_name='maindoctor',
            name='doctor_therapist',
        ),
        migrations.AddField(
            model_name='maindoctor',
            name='hospitals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='docs.hosp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurses',
            name='hospitals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='docs.hosp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='patient_nurse',
            field=models.ForeignKey(default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='docs.nurses'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hosp',
            name='hosp_docs',
            field=models.CharField(default=9, max_length=99),
        ),
        migrations.AlterField(
            model_name='maindoctor',
            name='doctor_age',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='maindoctor',
            name='doctor_experience',
            field=models.CharField(default=' 3 years ', max_length=10),
        ),
        migrations.AlterField(
            model_name='maindoctor',
            name='doctor_nurses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.nurses'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='doctor_nurses',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='docs.nurses'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='hospitals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.hosp'),
        ),
        migrations.AddField(
            model_name='maindoctor',
            name='mains_doctors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='docs.doctors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patients',
            name='patient_doc',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='docs.doctors'),
        ),
    ]
